name: CICD
run-name: CICD 🚀 ${{ github.actor }} 🤖
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Backend Folder
        run: |
          mkdir backend
          echo "Backend folder created successfully"

      - name: Checkout Additional Repository
        uses: actions/checkout@v4
        with:
          repository: 'https://github.com/BastiWho/Abschlussprojekt_Backend.git'
          path: 'backend'
      - name: Verify Additional Repository
        run: echo "Additional repository checked out successfully"
