name: CICD1

on:
  push:
    branches:
      - main
    paths:
      - '/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Backend Folder
        run: |
          mkdir backend
          echo "Backend folder created successfully"

      - name: Checkout Additional Repository
        uses: actions/checkout@v4
        with:
          repository: 'BastiWho/Abschlussprojekt_Backend'  # Updated to owner/repo format
          path: 'backend'
          
      - name: Verify Additional Repository
        run: echo "Additional repository checked out successfully"
