name: CICD
on:
  push:
    branches:
      - main
    paths:
      - '/'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create Backend Folder
        run: mkdir backend
      - uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'https://github.com/BastiWho/Abschlussprojekt_Backend.git'
          path: 'backend'